// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXh0XV1cw9UxOR6iJpUVlHOHfXPOTzmuQ',
    appId: '1:1001936688730:web:fe0464b5de559d6c3bea63',
    messagingSenderId: '1001936688730',
    projectId: 'nami-23edb',
    authDomain: 'nami-23edb.firebaseapp.com',
    storageBucket: 'nami-23edb.firebasestorage.app',
    measurementId: 'G-5RPGYTYDRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxaRe9y9qH0qdOT-pagnaRkskThRCz-Zs',
    appId: '1:1001936688730:android:098b22c4c9183bb13bea63',
    messagingSenderId: '1001936688730',
    projectId: 'nami-23edb',
    storageBucket: 'nami-23edb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4iivPE0dXLs9cOTSlyWdBklwzTfLDLW4',
    appId: '1:1001936688730:ios:cc20376cd74160853bea63',
    messagingSenderId: '1001936688730',
    projectId: 'nami-23edb',
    storageBucket: 'nami-23edb.firebasestorage.app',
    iosBundleId: 'com.example.nami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4iivPE0dXLs9cOTSlyWdBklwzTfLDLW4',
    appId: '1:1001936688730:ios:cc20376cd74160853bea63',
    messagingSenderId: '1001936688730',
    projectId: 'nami-23edb',
    storageBucket: 'nami-23edb.firebasestorage.app',
    iosBundleId: 'com.example.nami',
  );
}
